name: build-my-application

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    # Name the Job
    name: Build our app
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Print current directory
        run: pwd
      
      - name: List files in directory
        run: ls